  ignores: [
    ".next/**",
    "node_modules/**",
    ".agents/**",
    ".gemini/**",
    ".github/skills/**",
    ".claude/**",
    ".codex/**",
    ".superdesign/**",
    "test-results/**",
    "playwright-report/**",
    "storybook-static/**",
    ".storybook/**",
    "stories/**",
    ".kilo/**",
  ],